# Generated by Django 5.0.7 on 2025-01-06 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR')], max_length=3),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='plan_id',
            field=models.CharField(blank=True, help_text="Don't fill this field, This is automatically generated when created", max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='product_id',
            field=models.CharField(blank=True, help_text="Don't fill this field, This is automatically generated when created", max_length=100, null=True, unique=True),
        ),
    ]
