# Generated by Django 5.0.7 on 2024-12-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0004_alter_possiblelocation_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='possiblelocation',
            name='slug',
        ),
    ]
