# Generated by Django 5.0.7 on 2025-01-14 10:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votes', '0005_remove_possiblelocation_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='possiblelocation',
            name='votes',
            field=models.ManyToManyField(blank=True, related_name='user_vote', to=settings.AUTH_USER_MODEL),
        ),
    ]
