version: '3.9'

services:
  db:
    image: postgres
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis

  web:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8000:8000"

  celery:
    build: .
    depends_on:
      - db
      - redis
      - web
    command: ["celery", "-A", "tbcxfinal", "worker", "--loglevel=info"]

  celery-beat:
    build: .
    depends_on:
      - celery
    command: ["celery", "-A", "tbcxfinal", "beat", "--loglevel=info"]

volumes:
  postgres_data:
