# Generated by Django 5.0.7 on 2024-12-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_location_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='working_hours',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
