# Generated by Django 5.0.7 on 2024-12-15 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_location_working_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='slug',
        ),
    ]
