# Generated by Django 5.0.7 on 2024-12-16 16:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_location_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='views',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
