# Generated by Django 5.0.7 on 2025-01-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_location_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='anonymous_views',
            field=models.IntegerField(default=0),
        ),
    ]
